### ISSUE TITLE
Repo transferieren?

### ISSUE THREAD

**Issue by niccokunzmann** [speexy/biopunk.kitchen#2]
Wir können das in die biopunk.kitchen-orga tun.

Umsetzung:
- forken  
    erschwert es Pull-Requests entgegen zu nehmen, weil diese dann an dieses Repo gehen pre default.
- transfer (settings)  
    können wir machen, dann müssen Nutzer dieses Repos keine urls ändern. 
- clone + push --force  
    würde den Inhalt transferieren und dieses Repo würde bestehen bleiben.

Ich mag Tranfer: Wir können das, was ich gemacht habe, als zu biopunk.kitchen.github.io.old umbenennen und dann dieses mit [`npm run deploy`](https://github.com/bioPunkKitchen/bioPunkKitchen.github.io) durch github hosten.

Was magst du?

**Comment by speexy** [comment]
Ich bin nicht sicher, ob ich dich verstehe.

Also ich hätte jetzt einfach ein neues Repo erstellt und dort reingecloned. Bzw. hab schon. Also so ähnlich wie Punkt 3 bei dir?

Wegen den urls, das ist nicht so schlimm. 

Wegen hosting: Ich habe in dem Repo das Netlify CMS eingerichtet. Hosting läuft gratis über netlify. Damit kann Björn im CMS Content bearbeiten und publizieren, und das triggert dann automatisch nen build und die Seite wird aktualisiert. Man kann das Netlify CMS auch ohne Netlify Hosting nutzen, aber meines wissens kann man github nicht als server benutzen um dort nen spezifisches build script laufen zu lassen. 

Auch schön am Netlify CMS: Anmeldung geht mit Github Account. Hatte ich schon eingerichtet und mit Björn getestet, kann ich auch auf ein neues Repo übertragen. 

Außerdem fänd ichs schön, wenn wir die option haben, noch nen kleinen express-server einzubinden, falls wir z.B. ne search-box oderso einrichten wollen.

Wärst du einverstanden damit von einem frischen Repo zu starten? Und wenn ja, clone oder fork? 

Wenn wir uns entschieden habe, versuche ich das mit der domain ASAP einzurichten.

**Comment by niccokunzmann** [comment]
https://github.com/bioPunkKitchen/biopunk.kitchen existiert ja, bin ich zufrieden mit.
